### ISSUE TITLE
Builds with spear in the addon doesn't show spear in-game

### ISSUE THREAD

**Issue by ForgottenR** [xvwyh/BuildPad#15]
**Describe the bug**
Builds edited in the addon to have a spear doesn't show the spear in-game.
The other way around also doesn't work.
Seems like some inconsistency with internal weapon code or something similar.
Could also be a CN server only problem.

**To Reproduce**
1. Copy-paste a build with spear from the addon into the game chat and send it . 
2. View the chat link.

or
1. Copy-paste a build with spear from the game and add a build in the addon. 
2. View the build just added.

**Expected behavior**
Both ways should show the spear

**Screenshots**
None

**Comment by xvwyh** [comment]
Fixed in ea9e88a8a2bb0b24e09bc17274ca4bd5b53aedcf.
Turns out I incorrectly guessed the "ID"s of underwater weapons a year ago, in the SotO update which added the display of weapons to build chatlinks. And now, a year later, I forgot that back then I was guessing them, so I didn't really test it. Welp. Anyway, now, equipped with better datamining tools, I found the proper IDs of all underwater weapons, so now they all can be added to builds. Builds saved in the previous version, with the incorrect spear ID, will be automatically updated.
