### ISSUE TITLE
When used with d912pxy it causes memory leaks 

### ISSUE THREAD

**Issue by wolfrik17** [xvwyh/BuildPad#3]
After I installed BuildPad I started getting FPS drops at random times, d912pxy logs reported memory leaks. After removing BuildPad the memory leaks were gone and FPS was stable again.

**Comment by xvwyh** [comment]
Memory leaks are reported by d912pxy because I'm not deleting textures when GW2 is closing, but it shouldn't matter - the operating system will clean everything up. I added texture deletion in my local build, and the memory leak reports disappeared from the log.

But this cannot be causing FPS drops for you, as it only ever matters when you're already quitting the game. I'll play with d912pxy more, I guess, but I highly doubt your problems are caused by BuildPad. Unless you can pinpoint which exact actions lead to FPS drops - I can't help. If you don't have any BuildPad windows visible - it's completely dormant (with the exception of keybind handling), not even web requests are processed. And the only FPS drops that I know of that can happen WHILE interacting with BuildPad are when textures (skill, trait icons etc) are being loaded.

**Comment by wolfrik17** [comment]
I'll give it another try and see what happens or find a way to reproduce it easily
