### ISSUE TITLE
Suggestion from WvW main player about flags

### ISSUE THREAD

**Issue by soundofyogi** [xvwyh/BuildPad#5]
Hi, It's me again!

As WvW main, I see your [PvE] Categories is expanded as {Open World, Dungeon, Fractals, Raids}

Can we gat a bit love by expanding the [WvW] Categories into {Solo Roaming, Havocs, Zergs}
And also add 1 more roles in {Power, Condi, Tank, Support, Heal} with {Crowd Controls}

I mean crowd controls (Immobilize, Corrupt, Boonrip) is one of main roles in WvW

Thank you :)

**Comment by xvwyh** [comment]
I could add them, but what icons would you suggest I use for them? I'm not going to draw any myself, I only used in-game textures and I'd like to keep it that way for consistency (and laziness) sake.

**Comment by soundofyogi** [comment]
I gotcha!

Okay,  here's my suggestion

Zerg icon, you could use the commander tag graph: https://wiki.guildwars2.com/wiki/File:Commander_tag_(red).png

Havoc icon, let's use the catmander tag:
https://wiki.guildwars2.com/wiki/File:Catmander_tag_(red).png

For roamers, we can use the shared participation icon:
https://wiki.guildwars2.com/wiki/File:Squad_UI_shared_participation.png

And that's for WvW flags

and now to add the roles,

For Crowd controls, we can use many of cc effect icon, but i find daze icon is the most representative for it
https://wiki.guildwars2.com/wiki/File:Daze.png

I know it might sound selfish for not including PvP mode on this, but i found from godsofpvp site that the roles in PvP is Support, Teamfighter, Duelist and Roamers.
That 4 roles is already settled with the icons you have atm, Support is support, whilst the other 3 can fall into catagories of power/condi and tanks, so I guess it's already settled then? wdyt?

Anyhow, I am truly grateful you took your time doing all of this.

**Comment by xvwyh** [comment]
> I know it might sound selfish for not including PvP mode on this, but i found from godsofpvp site that the roles in PvP is Support, Teamfighter, Duelist and Roamers.

I have even less idea how to represent that in icons. For now I'll at least add filters for PvP gamemodes: Conquest, Stronghold, and let's throw Duos into the mix just in case, as they might be popular due to new off-seasons tournaments.

![image](https://user-images.githubusercontent.com/43143822/76534878-bd23fd80-6482-11ea-8c7d-98a983b0370a.png)

Progress so far. Still debating on the icon for Conquest mode and Control role. Instead of going with your suggestion of Daze icon, I went with the Stun icon instead, as Daze's swirly, I think, would look rather bad when separated from the background and scaled down. On the other hand, I'm not quite happy with how Stun looks either...

The new flags will be hidden-by-default, toggleable in the settings menu like shown on the screenshot. The number of icons there was quite overwhelming even on release, I don't want BuildPad window to take up half of the screen upon first launch.

**Comment by xvwyh** [comment]
Well, since you have no feedback - I released the new version with these flags, enjoy!

**Comment by soundofyogi** [comment]
Sorry was on vacation, but yeah this is great!
